[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "stegx"
version = "1.0.0"
description = "A CLI-based secure media steganography toolkit."
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "cryptography",
    "opencv-python",
    "pillow",
    "rich",
    "typer",
]

[project.scripts]
stegx = "stegx.cli:main"

[tool.setuptools.packages.find]
include = ["stegx*"]